server:
  port: 8011
  http2:
     enabled: true
  undertow:
    io-threads: 8
    worker-threads: 64
    buffer-size: 1024
    buffers-per-region: 1024
    direct-buffers: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.68.173.122:7158/saltyfish_generator?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useSSL=false
    username: amos_saltyfish
    password: amos0905saltyfish
  main:
    allow-bean-definition-overriding: true
  mvc:
     pathmatch:
       matching-strategy: ant_path_matcher
  security:
     oauth2:
       resourceserver:
         jwt:
           jwk-set-uri: http://localhost:9999/saltyfish-auth/rsa/publicKey
     user:
       name: amos
       password: Zz2825311647
       roles: SBA_ADMIN
  redis:
    database: 0
    host: 127.0.0.1
    port: 9736
    password: Zz2825311647
    lettuce:
      pool:
        min-idle: 1

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.saltyfish.admin.infrastructure.entity
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    call-setters-on-nulls: true

cache:
   # 缓存类型 redis、none(不使用缓存)
   type: none
   # 缓存时间(单位：ms)
   redis:
     time-to-live: 3600000
     # 缓存null值，防止缓存穿透
     cache-null-values: true
     # 允许使用缓存前缀
     use-key-prefix: true
     # 缓存前缀，没有设置使用注解的缓存名称(value)作为前缀，和注解的key用双冒号::拼接组成完整缓存key
     key-prefix: 'admin:'

# 阿里云短信配置
aliyun:
  sms:
    accessKeyId: LTAI5tSMgfxxxxxxdiBJLyR
    accessKeySecret: SoOWRqpjtS7xxxxxxZ2PZiMTJOVC
    domain: dysmsapi.aliyuncs.com
    regionId: cn-shanghai
    templateCode: SMS_22xxx770
    signName: 番薯

security:
  ignoreUrls:
      - /webjars/**
      - /doc.html
      - /swagger-resources/**
      - /v2/api-docs
      - /oauth/**
      - /rsa/publicKey
      - /sms-code